- block:
  - name: Cloning hlpylib
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlpylib.git'
      version: live
      dest: "{{virt_env_path}}/apps/hlpylib"
      clone: yes
    tags: hlpylib_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlpylib/requirements.txt"
    register: hlpylib_requirements_file

  - name: Install hlpylib requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlpylib"
    when: hlpylib_requirements_file.stat.exists == True
    tags: hlpylib_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlpylib/setup.py"
    register: hlpylib_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlpylib"
    when: hlpylib_setup_file.stat.exists == True
    tags: hlpylib_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
