- block:
  - name: Cloning hlmessagereceiver
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlmessagereceiver.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlmessagereceiver"
      clone: yes
    tags: hlmessagereceiver_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlmessagereceiver/requirements.txt"
    register: hlmessagereceiver_requirements_file

  - name: Install hlrpcfront requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlmessagereceiver"
    when: hlmessagereceiver_requirements_file.stat.exists == True
    tags: hlmessagereceiver_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlmessagereceiver/setup.py"
    register: hlmessagereceiver_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlmessagereceiver"
    when: hlmessagereceiver_setup_file.stat.exists == True
    tags: hlmessagereceiver_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
