- block:
  - name: Cloning hlexternallibs
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlexternallibs.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlexternallibs"
      clone: yes
    tags: hlexternallibs_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlexternallibs/requirements.txt"
    register: hlexternallibs_requirements_file

  - name: Install hlexternallibs requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlexternallibs"
    when: hlexternallibs_requirements_file.stat.exists == True
    tags: hlexternallibs_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlexternallibs/setup.py"
    register: hlexternallibs_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlexternallibs"
    when: hlexternallibs_setup_file.stat.exists == True
    tags: hlexternallibs_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
