- block:
  - name: Cloning hlwebservice
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlwebservice.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlwebservice"
      clone: yes
    tags: hlwebservice_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlwebservice/requirements.txt"
    register: hlwebservice_requirements_file

  - name: Install hlrpcfront requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlwebservice"
    when: hlwebservice_requirements_file.stat.exists == True
    tags: hlwebservice_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlwebservice/setup.py"
    register: hlwebservice_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlwebservice"
    when: hlwebservice_setup_file.stat.exists == True
    tags: hlwebservice_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
