- block:
  - name: Cloning hlreportgen
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlreportgen.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlreportgen"
      clone: yes
    tags: hlreportgen_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlreportgen/requirements.txt"
    register: hlreportgen_requirements_file

  - name: Install hlreportgen requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlreportgen"
    when: hlreportgen_requirements_file.stat.exists == True
    tags: hlreportgen_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlreportgen/setup.py"
    register: hlreportgen_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlreportgen"
    when: hlreportgen_setup_file.stat.exists == True
    tags: hlreportgen_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
