- name: Install python pip deps.
  pip:
    name: "{{hlrpc_pip_dep}}"
    state: present

- block:
  - name: Cloning hlrpcfront
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlrpcfront.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlrpcfront"
      clone: yes
    tags: hlrpcfront_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlrpcfront/requirements.txt"
    register: hlrpcfront_requirements_file

  - name: Install hlrpcfront requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlrpcfront"
    when: hlrpcfront_requirements_file.stat.exists == True
    tags: hlrpcfront_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlrpcfront/setup.py"
    register: hlrpcfront_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlrpcfront"
    when: hlrpcfront_setup_file.stat.exists == True
    tags: hlrpcfront_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
