- block:
  - name: Cloning hlvaluestorereader
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hlvaluestorereader.git'
      version: master
      dest: "{{virt_env_path}}/apps/hlvaluestorereader"
      clone: yes
    tags: hlvaluestorereader_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hlvaluestorereader/requirements.txt"
    register: hlvaluestorereader_requirements_file

  - name: Install hlvaluestorereader requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hlvaluestorereader"
    when: hlvaluestorereader_requirements_file.stat.exists == True
    tags: hlvaluestorereader_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hlvaluestorereader/setup.py"
    register: hlvaluestorereader_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hlvaluestorereader"
    when: hlvaluestorereader_setup_file.stat.exists == True
    tags: hlvaluestorereader_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
