- name: Installing RabbitMQ package.
  apt:
    name: rabbitmq-server
    state: present

- name: Enabling the rabbitmq_management
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled
  tags: enabled

- name: Adding admin to rabbitmq
  rabbitmq_user:
    user: admin
    password: "{{rbmq1_admin_password}}"
    state: present
    tags: administrator
    node: rabbit@staging-rbmq1
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*

- name: Adding monitorscout to rabbitmq
  rabbitmq_user:
    user: monitorscout
    password: "{{rbmq1_monitorscout_password}}"
    state: present
    node: rabbit@staging-rbmq1
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*

- name: Removing guest user.
  rabbitmq_user:
    user: guest
    state: absent
    node: rabbit@staging-rbmq1
  notify: restart rabbitmq-server
