- block:
  - name: Cloning hldpbridge
    git:
      repo: 'http://{{git_user}}:{{git_token}}@hl.test.io/monitoring/monitorscout/hldpbridge.git'
      version: master
      dest: "{{virt_env_path}}/apps/hldpbridge"
      clone: yes
    tags: hldpbridge_clone

  - name: Checking the requirements.txt
    stat:
      path: "{{virt_env_path}}/apps/hldpbridge/requirements.txt"
    register: hldpbridge_requirements_file

  - name: Install hldpbridge requirements
    command: pipenv run pip install -r requirements.txt
    args:
      chdir: "{{virt_env_path}}/apps/hldpbridge"
    when: hldpbridge_requirements_file.stat.exists == True
    tags: hldpbridge_requirefile_install

  - name: Checking setup.py file
    stat:
      path: "{{virt_env_path}}/apps/hldpbridge/setup.py"
    register: hldpbridge_setup_file

  - name: Setting up applications pipenv run python setup.py install
    command: pipenv run python setup.py install
    args:
      chdir: "{{virt_env_path}}/apps/hldpbridge"
    when: hldpbridge_setup_file.stat.exists == True
    tags: hldpbridge_setupfile_install

  become: true
  become_user: "{{becomeusr}}"
  become_method: sudo
